global:
  env : "dev"
  name : "dexco-ecs"
  region: "eu-central-1" 
  tags:
    documentation : "https://github.com/alessonviana/Desafio-T-cnico---DevOps-Dexco/blob/main/README.md"
    managed_by : "terraform"
    repository: "https://github.com/alessonviana/Desafio-T-cnico---DevOps-Dexco"