global:
  env: "dev"
  cluster_name: "dexco-ecs"
  repository: "https://github.com/alessonviana/Desafio-T-cnico---DevOps-Dexco"
  region: "eu-central-1" #Selecione sua região.
  vpc_id: "" #Selecione sua VPC ID.
  alb:  #Selecione o nome do seu ALB.
  tags:
    documentation : "https://github.com/alessonviana/Desafio-T-cnico---DevOps-Dexco/blob/main/README.md"
    managed_by : "terraform"
    repository: "https://github.com/alessonviana/Desafio-T-cnico---DevOps-Dexco"

microservices:
  pisos:
    service_name: "pisos"
    path: ["/pisos"]
    health_check_path: "/healthcheck"
    health_check_grace_period_seconds: 0
    desired_count: 1
    port: 3000
    policies: ["arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
               "arn:aws:iam::aws:policy/CloudWatchFullAccess",
               "arn:aws:iam::aws:policy/AmazonS3FullAccess"]

#Para mais microserviços, basta adicionar como o exemplo abaixo:
  #app2
    # service_name: "app2"
    # path: ["/myapp"]
    # health_check_path: "/"
    # health_check_grace_period_seconds: 0
    # desired_count: 1
    # port: 80
    # policies: ["arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    #            "arn:aws:iam::aws:policy/CloudWatchFullAccess",
    #            "arn:aws:iam::aws:policy/AmazonS3FullAccess"]